{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "9654e82b-99ea-4f89-9038-ac878b2cf980",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: numpy in /opt/anaconda3/lib/python3.13/site-packages (2.1.3)\n",
      "Requirement already satisfied: scipy in /opt/anaconda3/lib/python3.13/site-packages (1.15.3)\n",
      "Requirement already satisfied: pandas in /opt/anaconda3/lib/python3.13/site-packages (2.2.3)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2024.1)\n",
      "Requirement already satisfied: tzdata>=2022.7 in /opt/anaconda3/lib/python3.13/site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in /opt/anaconda3/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Note: you may need to restart the kernel to use updated packages.\n"
     ]
    }
   ],
   "source": [
    "pip install numpy scipy pandas"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "be822739-7b17-47d3-a3d9-1fa20f166fa8",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "============================================================\n",
      "  CTMC NETWORKED SYSTEM RELIABILITY ANALYSIS\n",
      "  15 components | 100,000 Monte Carlo runs\n",
      "============================================================\n",
      "\n",
      "[1] ANALYTICAL COMPONENT METRICS\n",
      " Comp        λ        μ    Avail   MTTF(hr)   MTTR(hr)\n",
      "    1   0.0020   0.1000   0.9804      500.0      10.00\n",
      "    2   0.0030   0.0800   0.9639      333.3      12.50\n",
      "    3   0.0010   0.1200   0.9917     1000.0       8.33\n",
      "    4   0.0040   0.0900   0.9574      250.0      11.11\n",
      "    5   0.0020   0.1100   0.9821      500.0       9.09\n",
      "    6   0.0050   0.0700   0.9333      200.0      14.29\n",
      "    7   0.0030   0.1000   0.9709      333.3      10.00\n",
      "    8   0.0020   0.0900   0.9783      500.0      11.11\n",
      "    9   0.0010   0.1300   0.9924     1000.0       7.69\n",
      "   10   0.0040   0.0800   0.9524      250.0      12.50\n",
      "   11   0.0030   0.1000   0.9709      333.3      10.00\n",
      "   12   0.0020   0.1100   0.9821      500.0       9.09\n",
      "   13   0.0050   0.0700   0.9333      200.0      14.29\n",
      "   14   0.0010   0.1200   0.9917     1000.0       8.33\n",
      "   15   0.0030   0.0900   0.9677      333.3      11.11\n",
      "\n",
      "[2] SYSTEM TOPOLOGY RELIABILITY (Analytical)\n",
      "  Series system:        0.630614\n",
      "  Parallel system:      1.000000\n",
      "  8-out-of-15 system:   1.000000\n",
      "  10-out-of-15 system:  0.999997\n",
      "\n",
      "[3] CTMC TIME-DEPENDENT AVAILABILITY (Component 1)\n",
      "  t=   10hr: A(t) = 0.987463\n",
      "  t=  100hr: A(t) = 0.980393\n",
      "  t=  500hr: A(t) = 0.980392\n",
      "  t= 1000hr: A(t) = 0.980392\n",
      "\n",
      "[4] MONTE CARLO SIMULATION (100,000 runs) ...\n",
      "  Mean component availability: 0.9702\n",
      "  System availability (8/15):  1.0000\n",
      "  Est. system MTTF:            25.32 hr\n",
      "  Avg failures per component:  2.63\n",
      "\n",
      "  Validation — Analytical mean avail: 0.9699 | MC estimate: 0.9702 | Error: 0.0003\n",
      "\n",
      "[5] SENSITIVITY ANALYSIS (Analytical, ±10% perturbation)\n",
      " Component  λ_sensitivity  μ_sensitivity  baseline_avail\n",
      "         1      -0.000001       0.000000        0.980400\n",
      "         2      -0.000001       0.000000        0.963900\n",
      "         3      -0.000001       0.000000        0.991700\n",
      "         4      -0.000001       0.000000        0.957400\n",
      "         5      -0.000001       0.000000        0.982100\n",
      "         6      -0.000001       0.000000        0.933300\n",
      "         7      -0.000001       0.000000        0.970900\n",
      "         8      -0.000001       0.000000        0.978300\n",
      "         9      -0.000000       0.000000        0.992400\n",
      "        10      -0.000001       0.000000        0.952400\n",
      "        11      -0.000001       0.000000        0.970900\n",
      "        12      -0.000001       0.000000        0.982100\n",
      "        13      -0.000001       0.000000        0.933300\n",
      "        14      -0.000001       0.000000        0.991700\n",
      "        15      -0.000001       0.000000        0.967700\n",
      "\n",
      "  Top 3 components by λ-sensitivity: [9, 1, 2]\n",
      "  Top 3 components by μ-sensitivity: [1, 2, 3]\n",
      "\n",
      "[6] IMPORTANCE SAMPLING — Rare Event Estimation\n",
      "  Target:                      P(≥5 components fail ≥1 time in 1000.0hr)\n",
      "  IS estimate:                 4.2484e-18\n",
      "  Standard error:              1.0336e-35\n",
      "  95% CI:                      (4.2484e-18, 4.2484e-18)\n",
      "\n",
      "[7] REDUNDANCY ALLOCATION (Budget = $5,000)\n",
      "  Baseline reliability:    0.630614\n",
      "  Optimized reliability:   0.834211\n",
      "  Improvement:             +0.203597\n",
      "  Total cost spent:        $5,000\n",
      "  Redundancy per component: [0, 1, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1]\n",
      "\n",
      "============================================================\n",
      "  ALL ANALYSES COMPLETE\n",
      "============================================================\n"
     ]
    }
   ],
   "source": [
    "\"\"\"\n",
    "Networked System Reliability Analysis\n",
    "======================================\n",
    "15-component system modeled with Continuous-Time Markov Chains (CTMC)\n",
    "Covers:\n",
    "  - Monte Carlo simulation (10^5+ runs)\n",
    "  - Availability, failure frequency, MTTF estimation\n",
    "  - Series, parallel, k-out-of-n system reliability\n",
    "  - Closed-form analytical validation\n",
    "  - Sensitivity analysis on λ and μ\n",
    "  - Importance sampling for rare-event estimation\n",
    "  - Redundancy allocation under cost constraints\n",
    "\"\"\"\n",
    "\n",
    "import numpy as np\n",
    "import pandas as pd\n",
    "from scipy.linalg import expm\n",
    "from scipy.optimize import minimize\n",
    "import warnings\n",
    "warnings.filterwarnings(\"ignore\")\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 1. SYSTEM CONFIGURATION\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "N_COMPONENTS = 15\n",
    "N_SIMULATIONS = 100_000\n",
    "T_MISSION = 1000.0       # mission time (hours)\n",
    "RANDOM_SEED = 42\n",
    "rng = np.random.default_rng(RANDOM_SEED)\n",
    "\n",
    "# Real-world-inspired failure & repair rates (per hour)\n",
    "# Source profile: industrial electronic/mechanical components\n",
    "LAMBDA = np.array([\n",
    "    0.002, 0.003, 0.001, 0.004, 0.002,\n",
    "    0.005, 0.003, 0.002, 0.001, 0.004,\n",
    "    0.003, 0.002, 0.005, 0.001, 0.003\n",
    "])  # failure rates λ_i\n",
    "\n",
    "MU = np.array([\n",
    "    0.10, 0.08, 0.12, 0.09, 0.11,\n",
    "    0.07, 0.10, 0.09, 0.13, 0.08,\n",
    "    0.10, 0.11, 0.07, 0.12, 0.09\n",
    "])  # repair rates μ_i\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 2. ANALYTICAL STEADY-STATE (per component)\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def component_availability(lam, mu):\n",
    "    \"\"\"Steady-state availability: A = μ / (λ + μ)\"\"\"\n",
    "    return mu / (lam + mu)\n",
    "\n",
    "def component_mttf(lam):\n",
    "    \"\"\"Mean Time To Failure for a single component: 1/λ\"\"\"\n",
    "    return 1.0 / lam\n",
    "\n",
    "def component_mttr(mu):\n",
    "    \"\"\"Mean Time To Repair: 1/μ\"\"\"\n",
    "    return 1.0 / mu\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 3. SYSTEM TOPOLOGY RELIABILITY (Analytical)\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def series_reliability(availabilities):\n",
    "    \"\"\"All components must work: R_s = Π A_i\"\"\"\n",
    "    return np.prod(availabilities)\n",
    "\n",
    "def parallel_reliability(availabilities):\n",
    "    \"\"\"At least one must work: R_p = 1 - Π(1 - A_i)\"\"\"\n",
    "    return 1.0 - np.prod(1.0 - availabilities)\n",
    "\n",
    "def k_out_of_n_reliability(availabilities, k):\n",
    "    \"\"\"\n",
    "    Exactly k-out-of-n components must work.\n",
    "    Assumes homogeneous p = mean(availabilities) for tractability.\n",
    "    \"\"\"\n",
    "    from math import comb\n",
    "    n = len(availabilities)\n",
    "    p = np.mean(availabilities)\n",
    "    q = 1.0 - p\n",
    "    return sum(comb(n, i) * (p**i) * (q**(n-i)) for i in range(k, n+1))\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 4. CTMC GENERATOR MATRIX (2-state per component)\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def build_generator(lam, mu):\n",
    "    \"\"\"\n",
    "    For a single component:\n",
    "      State 0 = Working, State 1 = Failed\n",
    "      Q = [[-λ,  λ],\n",
    "           [ μ, -μ]]\n",
    "    \"\"\"\n",
    "    Q = np.array([[-lam, lam],\n",
    "                  [ mu, -mu]])\n",
    "    return Q\n",
    "\n",
    "def ctmc_availability(lam, mu, t):\n",
    "    \"\"\"\n",
    "    Time-dependent availability via matrix exponential:\n",
    "      P(t) = exp(Q*t), starting in state 0 (working)\n",
    "    \"\"\"\n",
    "    Q = build_generator(lam, mu)\n",
    "    Pt = expm(Q * t)\n",
    "    return Pt[0, 0]   # P(working at t | working at 0)\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 5. MONTE CARLO SIMULATION\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def simulate_component(lam, mu, T, rng):\n",
    "    \"\"\"\n",
    "    Simulate one component over [0, T] using competing exponentials.\n",
    "    Returns: (time_working, n_failures)\n",
    "    \"\"\"\n",
    "    t = 0.0\n",
    "    state = 1  # 1=working, 0=failed\n",
    "    time_working = 0.0\n",
    "    n_failures = 0\n",
    "\n",
    "    while t < T:\n",
    "        if state == 1:\n",
    "            dt = rng.exponential(1.0 / lam)\n",
    "            dt = min(dt, T - t)\n",
    "            time_working += dt\n",
    "            t += dt\n",
    "            if t < T:\n",
    "                state = 0\n",
    "                n_failures += 1\n",
    "        else:\n",
    "            dt = rng.exponential(1.0 / mu)\n",
    "            t += dt\n",
    "            if t < T:\n",
    "                state = 1\n",
    "\n",
    "    return time_working, n_failures\n",
    "\n",
    "\n",
    "def run_monte_carlo(LAMBDA, MU, T, n_sims, k_threshold=8, rng=None):\n",
    "    \"\"\"\n",
    "    Run n_sims Monte Carlo trials for the 15-component system.\n",
    "    Records per-trial: availability, failure counts, system-level status.\n",
    "    \"\"\"\n",
    "    if rng is None:\n",
    "        rng = np.random.default_rng(42)\n",
    "\n",
    "    n = len(LAMBDA)\n",
    "    availabilities = np.zeros(n_sims)\n",
    "    failure_counts = np.zeros((n_sims, n), dtype=int)\n",
    "    system_up_time = np.zeros(n_sims)\n",
    "\n",
    "    for sim in range(n_sims):\n",
    "        comp_avail = np.zeros(n)\n",
    "        comp_failures = np.zeros(n, dtype=int)\n",
    "        for i in range(n):\n",
    "            tw, nf = simulate_component(LAMBDA[i], MU[i], T, rng)\n",
    "            comp_avail[i] = tw / T\n",
    "            comp_failures[i] = nf\n",
    "        failure_counts[sim] = comp_failures\n",
    "        # System availability: k-out-of-n (k=8 of 15 must work)\n",
    "        n_working = np.sum(comp_avail > 0.5)\n",
    "        availabilities[sim] = np.mean(comp_avail)\n",
    "        system_up_time[sim] = 1.0 if n_working >= k_threshold else 0.0\n",
    "\n",
    "    return {\n",
    "        \"mean_availability\":      np.mean(availabilities),\n",
    "        \"std_availability\":       np.std(availabilities),\n",
    "        \"system_availability\":    np.mean(system_up_time),\n",
    "        \"mean_failures_per_comp\": np.mean(failure_counts, axis=0),\n",
    "        \"total_failures\":         failure_counts.sum(axis=1),\n",
    "        \"mttf_estimate\":          T / (failure_counts.sum(axis=1).mean() + 1e-9),\n",
    "    }\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 6. SENSITIVITY ANALYSIS\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def sensitivity_analysis(LAMBDA, MU, perturbation=0.10):\n",
    "    \"\"\"\n",
    "    Analytical sensitivity: perturb each λ_i and μ_i and measure change\n",
    "    in system-level k-out-of-n reliability using closed-form availability.\n",
    "    No Monte Carlo noise — fully deterministic.\n",
    "    \"\"\"\n",
    "    avail_base = component_availability(LAMBDA, MU)\n",
    "    baseline = k_out_of_n_reliability(avail_base, k=8)\n",
    "    results = []\n",
    "\n",
    "    for i in range(len(LAMBDA)):\n",
    "        # Perturb λ_i upward (higher failure rate → lower availability)\n",
    "        L_up = LAMBDA.copy(); L_up[i] *= (1 + perturbation)\n",
    "        A_lam = component_availability(L_up, MU)\n",
    "        sys_lam = k_out_of_n_reliability(A_lam, k=8)\n",
    "        lam_sens = (sys_lam - baseline) / (perturbation * LAMBDA[i])\n",
    "\n",
    "        # Perturb μ_i upward (faster repair → higher availability)\n",
    "        M_up = MU.copy(); M_up[i] *= (1 + perturbation)\n",
    "        A_mu = component_availability(LAMBDA, M_up)\n",
    "        sys_mu = k_out_of_n_reliability(A_mu, k=8)\n",
    "        mu_sens = (sys_mu - baseline) / (perturbation * MU[i])\n",
    "\n",
    "        results.append({\n",
    "            \"Component\": i + 1,\n",
    "            \"λ_sensitivity\": round(lam_sens, 6),\n",
    "            \"μ_sensitivity\": round(mu_sens, 6),\n",
    "            \"baseline_avail\": round(component_availability(LAMBDA[i], MU[i]), 4),\n",
    "        })\n",
    "\n",
    "    return pd.DataFrame(results)\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 7. IMPORTANCE SAMPLING (Rare Event Estimation)\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "def importance_sampling_rare_failure(LAMBDA, MU, T, n_sims=50_000,\n",
    "                                     failure_threshold=5, rng=None):\n",
    "    \"\"\"\n",
    "    Estimate P(≥ failure_threshold components fail at least once during [0,T])\n",
    "    using importance sampling with inflated Poisson failure counts.\n",
    "\n",
    "    For each component, the number of failures in [0,T] under the true\n",
    "    distribution is Poisson(λ_i·T). Under the IS distribution it is\n",
    "    Poisson(λ_IS_i·T). The likelihood ratio per component is:\n",
    "\n",
    "        w_i = Pois(n_i; λ_i·T) / Pois(n_i; λ_IS_i·T)\n",
    "            = exp((λ_IS_i - λ_i)·T) · (λ_i/λ_IS_i)^n_i\n",
    "    \"\"\"\n",
    "    if rng is None:\n",
    "        rng = np.random.default_rng(42)\n",
    "\n",
    "    beta = 5.0\n",
    "    LAMBDA_IS = LAMBDA * beta\n",
    "    rate_true = LAMBDA * T\n",
    "    rate_IS   = LAMBDA_IS * T\n",
    "\n",
    "    estimates = []\n",
    "    for _ in range(n_sims):\n",
    "        # Sample failure counts under IS distribution\n",
    "        n_fail = rng.poisson(rate_IS)           # shape (N,)\n",
    "        # Indicator: ≥ failure_threshold components experienced ≥1 failure\n",
    "        n_failed_comps = np.sum(n_fail >= 1)\n",
    "        indicator = float(n_failed_comps >= failure_threshold)\n",
    "        # Log likelihood ratio (sum over components)\n",
    "        log_w = np.sum((rate_IS - rate_true) + n_fail * np.log(rate_true / rate_IS))\n",
    "        w = np.exp(np.clip(log_w, -40, 20))\n",
    "        estimates.append(indicator * w)\n",
    "\n",
    "    estimates = np.array(estimates)\n",
    "    p_est = float(np.mean(estimates))\n",
    "    se    = float(np.std(estimates) / np.sqrt(n_sims))\n",
    "\n",
    "    return {\n",
    "        \"P_rare_failure_IS\": p_est,\n",
    "        \"standard_error\":    se,\n",
    "        \"95pct_CI\":          (max(0.0, p_est - 1.96 * se), p_est + 1.96 * se),\n",
    "        \"target\":            f\"P(≥{failure_threshold} components fail ≥1 time in {T}hr)\",\n",
    "    }\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 8. REDUNDANCY ALLOCATION UNDER COST CONSTRAINTS\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "COMPONENT_COSTS = np.array([\n",
    "    500, 800, 300, 1000, 600,\n",
    "    900, 700, 500, 400,  800,\n",
    "    600, 500, 900, 350,  700\n",
    "])  # unit cost per additional redundant component ($)\n",
    "\n",
    "TOTAL_BUDGET = 5000  # total redundancy budget ($)\n",
    "\n",
    "def system_reliability_with_redundancy(redundancy, LAMBDA, MU):\n",
    "    \"\"\"\n",
    "    Each component i has (1 + redundancy[i]) parallel copies.\n",
    "    System reliability = series of parallel subsystems.\n",
    "    \"\"\"\n",
    "    avail = component_availability(LAMBDA, MU)\n",
    "    subsystem_reliabilities = []\n",
    "    for i, r in enumerate(redundancy):\n",
    "        r = int(round(r))\n",
    "        n_copies = 1 + r\n",
    "        # Parallel reliability for n_copies of component i\n",
    "        sub_r = 1.0 - (1.0 - avail[i]) ** n_copies\n",
    "        subsystem_reliabilities.append(sub_r)\n",
    "    return np.prod(subsystem_reliabilities)   # series of subsystems\n",
    "\n",
    "def optimize_redundancy(LAMBDA, MU, costs, budget, max_redundancy=3):\n",
    "    \"\"\"\n",
    "    Maximize system reliability subject to budget constraint.\n",
    "    Uses a greedy marginal-gain algorithm suitable for integer allocation.\n",
    "    At each step: add one redundant unit to the component with highest\n",
    "    reliability gain per dollar, until budget exhausted.\n",
    "    \"\"\"\n",
    "    n = len(LAMBDA)\n",
    "    avail = component_availability(LAMBDA, MU)\n",
    "\n",
    "    def subsystem_r(i, r):\n",
    "        \"\"\"Parallel reliability of (1+r) copies of component i.\"\"\"\n",
    "        return 1.0 - (1.0 - avail[i]) ** (1 + r)\n",
    "\n",
    "    def system_r(redun):\n",
    "        return np.prod([subsystem_r(i, r) for i, r in enumerate(redun)])\n",
    "\n",
    "    redun = np.zeros(n, dtype=int)\n",
    "    remaining = budget\n",
    "    baseline = system_r(redun)\n",
    "\n",
    "    for _ in range(budget):   # at most budget/min_cost iterations\n",
    "        best_i, best_gain_per_dollar = -1, 0.0\n",
    "        for i in range(n):\n",
    "            if redun[i] >= max_redundancy:\n",
    "                continue\n",
    "            if costs[i] > remaining:\n",
    "                continue\n",
    "            # Marginal gain from adding one unit to component i\n",
    "            gain = (subsystem_r(i, redun[i] + 1) - subsystem_r(i, redun[i]))\n",
    "            gain_per_dollar = gain / costs[i]\n",
    "            if gain_per_dollar > best_gain_per_dollar:\n",
    "                best_gain_per_dollar = gain_per_dollar\n",
    "                best_i = i\n",
    "        if best_i < 0:\n",
    "            break\n",
    "        redun[best_i] += 1\n",
    "        remaining -= costs[best_i]\n",
    "\n",
    "    return {\n",
    "        \"optimal_redundancy\":     redun,\n",
    "        \"total_cost\":             int(budget - remaining),\n",
    "        \"baseline_reliability\":   round(baseline, 8),\n",
    "        \"optimized_reliability\":  round(system_r(redun), 8),\n",
    "    }\n",
    "\n",
    "\n",
    "# ─────────────────────────────────────────────\n",
    "# 9. MAIN — RUN ALL ANALYSES\n",
    "# ─────────────────────────────────────────────\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    sep = \"=\" * 60\n",
    "\n",
    "    print(sep)\n",
    "    print(\"  CTMC NETWORKED SYSTEM RELIABILITY ANALYSIS\")\n",
    "    print(f\"  {N_COMPONENTS} components | {N_SIMULATIONS:,} Monte Carlo runs\")\n",
    "    print(sep)\n",
    "\n",
    "    # ── Analytical per-component metrics ──\n",
    "    avail_analytical = component_availability(LAMBDA, MU)\n",
    "    print(\"\\n[1] ANALYTICAL COMPONENT METRICS\")\n",
    "    print(f\"{'Comp':>5} {'λ':>8} {'μ':>8} {'Avail':>8} {'MTTF(hr)':>10} {'MTTR(hr)':>10}\")\n",
    "    for i in range(N_COMPONENTS):\n",
    "        print(f\"{i+1:>5} {LAMBDA[i]:>8.4f} {MU[i]:>8.4f} \"\n",
    "              f\"{avail_analytical[i]:>8.4f} \"\n",
    "              f\"{component_mttf(LAMBDA[i]):>10.1f} \"\n",
    "              f\"{component_mttr(MU[i]):>10.2f}\")\n",
    "\n",
    "    # ── System topology ──\n",
    "    print(\"\\n[2] SYSTEM TOPOLOGY RELIABILITY (Analytical)\")\n",
    "    print(f\"  Series system:        {series_reliability(avail_analytical):.6f}\")\n",
    "    print(f\"  Parallel system:      {parallel_reliability(avail_analytical):.6f}\")\n",
    "    print(f\"  8-out-of-15 system:   {k_out_of_n_reliability(avail_analytical, k=8):.6f}\")\n",
    "    print(f\"  10-out-of-15 system:  {k_out_of_n_reliability(avail_analytical, k=10):.6f}\")\n",
    "\n",
    "    # ── CTMC time-dependent availability ──\n",
    "    print(\"\\n[3] CTMC TIME-DEPENDENT AVAILABILITY (Component 1)\")\n",
    "    for t in [10, 100, 500, 1000]:\n",
    "        print(f\"  t={t:>5}hr: A(t) = {ctmc_availability(LAMBDA[0], MU[0], t):.6f}\")\n",
    "\n",
    "    # ── Monte Carlo ──\n",
    "    print(f\"\\n[4] MONTE CARLO SIMULATION ({N_SIMULATIONS:,} runs) ...\")\n",
    "    mc = run_monte_carlo(LAMBDA, MU, T_MISSION, N_SIMULATIONS, k_threshold=8, rng=rng)\n",
    "    print(f\"  Mean component availability: {mc['mean_availability']:.4f}\")\n",
    "    print(f\"  System availability (8/15):  {mc['system_availability']:.4f}\")\n",
    "    print(f\"  Est. system MTTF:            {mc['mttf_estimate']:.2f} hr\")\n",
    "    print(f\"  Avg failures per component:  {mc['mean_failures_per_comp'].mean():.2f}\")\n",
    "\n",
    "    # Validate MC vs analytical\n",
    "    analytical_avail = np.mean(avail_analytical)\n",
    "    print(f\"\\n  Validation — Analytical mean avail: {analytical_avail:.4f} | \"\n",
    "          f\"MC estimate: {mc['mean_availability']:.4f} | \"\n",
    "          f\"Error: {abs(analytical_avail - mc['mean_availability']):.4f}\")\n",
    "\n",
    "    # ── Sensitivity analysis ──\n",
    "    print(\"\\n[5] SENSITIVITY ANALYSIS (Analytical, ±10% perturbation)\")\n",
    "    sens = sensitivity_analysis(LAMBDA, MU)\n",
    "    print(sens.to_string(index=False, float_format=\"{:.6f}\".format))\n",
    "\n",
    "    top_lam = sens.nlargest(3, \"λ_sensitivity\")[\"Component\"].tolist()\n",
    "    top_mu  = sens.nlargest(3, \"μ_sensitivity\")[\"Component\"].tolist()\n",
    "    print(f\"\\n  Top 3 components by λ-sensitivity: {top_lam}\")\n",
    "    print(f\"  Top 3 components by μ-sensitivity: {top_mu}\")\n",
    "\n",
    "    # ── Importance sampling ──\n",
    "    print(\"\\n[6] IMPORTANCE SAMPLING — Rare Event Estimation\")\n",
    "    is_result = importance_sampling_rare_failure(\n",
    "        LAMBDA, MU, T_MISSION, n_sims=50_000, failure_threshold=5, rng=rng\n",
    "    )\n",
    "    print(f\"  Target:                      {is_result['target']}\")\n",
    "    print(f\"  IS estimate:                 {is_result['P_rare_failure_IS']:.4e}\")\n",
    "    print(f\"  Standard error:              {is_result['standard_error']:.4e}\")\n",
    "    lo, hi = is_result[\"95pct_CI\"]\n",
    "    print(f\"  95% CI:                      ({lo:.4e}, {hi:.4e})\")\n",
    "\n",
    "    # ── Redundancy optimization ──\n",
    "    print(\"\\n[7] REDUNDANCY ALLOCATION (Budget = $5,000)\")\n",
    "    opt = optimize_redundancy(LAMBDA, MU, COMPONENT_COSTS, TOTAL_BUDGET)\n",
    "    print(f\"  Baseline reliability:    {opt['baseline_reliability']:.6f}\")\n",
    "    print(f\"  Optimized reliability:   {opt['optimized_reliability']:.6f}\")\n",
    "    print(f\"  Improvement:             +{opt['optimized_reliability'] - opt['baseline_reliability']:.6f}\")\n",
    "    print(f\"  Total cost spent:        ${opt['total_cost']:,}\")\n",
    "    print(f\"  Redundancy per component: {opt['optimal_redundancy'].tolist()}\")\n",
    "\n",
    "    print(f\"\\n{sep}\")\n",
    "    print(\"  ALL ANALYSES COMPLETE\")\n",
    "    print(sep)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "70cc24d2-7853-4dea-98f2-53c926e3ff0e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.5"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
